### ISSUE TITLE
Change license from MIT to GPLV3

### ISSUE THREAD

**Issue by hcwinsemius** [localdevices/odm360#134]
I would prefer to see a clear share alike license on our IP. So herewith my suggestion to change the license and add a clear AUTHORS.txt for all contributors.

**Comment by smathermather** [comment]
I am in full agreement.

**Comment by ivangayton** [comment]
Yes and also fuck yeah.

Ivan Buendía Gayton

+1 510 241 8984 (phone, Signal, WhatsApp)
Skype: sardo.numpsi

This message was sent from a zucchini, possibly using voice transcription.
Please excuse any typos.

**Comment by hcwinsemius** [comment]
A-GPL 3 now implemented, closing issue
