### ISSUE TITLE
Provisioning scripts don't work with Raspberry Pi Desktop, only lite

### ISSUE THREAD

**Issue by smathermather** [localdevices/odm360#140]
To replicate: install on Raspberry Pi Desktop. After install and reboot, screen is blank.

It works fine on a Raspberry Pi OS Lite / headless.

I have not yet looked into why this is happening.

**Comment by hcwinsemius** [comment]
hi Steve, any news on this? Still relevant or not?

**Comment by smathermather** [comment]
It's probably still an issue, but I don't know if we need to track this. I'll close it, and if it becomes an issue for someone, we can reopen and investigate.
